services:
  mariadb:
    image: mariadb:lts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payments
      MYSQL_USER: payments
      MYSQL_PASSWORD: payments
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb:/var/lib/mysql
